#!/usr/bin/bash

set -e

#for location management
yay -S geoclue 
systemctl --user daemon-reload
systemctl --user enable geoclue-agent.service
systemctl --user start geoclue-agent.service

# for battery management
yay -S upower
systemctl --user daemon-reload
sudo systemctl enable upower.service
sudo systemctl  start upower.service

