#!/usr/bin/bash

set -e

#for location management
yay -S geoclue 
systemctl --user daemon-reload
systemctl --user enable geoclue-agent.service
systemctl --user start geoclue-agent.service

# for battery management
yay -S upower
systemctl --user daemon-reload
sudo systemctl enable upower.service
sudo systemctl  start upower.service

if ! cd $HOME/github/joshuar/go-hass-agent; then
  mkdir $HOME/github/joshuar -p
  cd $HOME/github/joshuar
  git clone ssh://git@github.com/joshuar/go-hass-agent.git
  cd go-hass-agent
fi
if ! git remote -v | grep -i upstream; then
  git remote rename origin upstream
  git remote add origin git@github.com:kamaradclimber/go-hass-agent.git
fi

go build

systemctl --user daemon-reload
systemctl --user enable go-hass-agent.service
systemctl --user start  go-hass-agent.service
