#!/usr/bin/bash

DEST_DIR=$HOME/hydrao-dump
git clone https://github.com/kamaradclimber/hydrao-dump $DEST_DIR
cd $DEST_DIR

systemctl --user daemon-reload
systemctl --user enable hydrao-dump
systemctl --user start hydrao-dump
