#!/usr/bin/env bash

# this script tries to be compatible with all types of systems I work on:
# - my macos work laptop
# - dd workspaces
# - my personal linux desktop

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $HOME

touch .gitconfig

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "work laptop"
  echo <<EOF >> .gitconfig
  [include]
    path = $SCRIPT_DIR/dot-gitconfig-work
EOF
else if grep -q "@datadoghq.com" .gitconfig; then
  echo "dd workspace"
  echo <<EOF >> .gitconfig
  [include]
    path = $SCRIPT_DIR/dot-gitconfig-work
else
  echo "linux"
  echo <<EOF >> .gitconfig
  [include]
    path = $SCRIPT_DIR/dot-gitconfig-personal
EOF
fi
