#!/usr/bin/bash

# dunst related configuration

echo Make sure we have only a single notification server
if [[ "$(grep -r Notifications /usr/share/dbus-1/services/ | grep -v dunst)" -ne "0" ]]; then
  echo There are several notification systems in addition to dunst, please uninstall them
fi

yay -S dunst


# i3-companion
#
mkdir $HOME/.cache
cd $HOME/.cache
virtualenv i3-companion
source i3-companion/bin/activate
pip install dbussy i3ipc xcffib systemd-python
