# to validate the conf:
# sudo -u hass hass --script check_config --files -c /var/lib/hass
homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret location_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 66 # altitude
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  customize_domain:
    device_tracker:
      icon: mdi:network-question
  customize:
    switch.capodimonte_led:
      icon: mdi:led-variant-on
    script.radio_swiss_classic:
      icon: mdi:radio
    device_tracker.kodi:
      icon: mdi:projector
    script.bedtime:
      icon: mdi:hotel
    script.restart_ha:
      icon: mdi:restart
    scene.movie_paused:
      icon: mdi:play-pause
    scene.movie_playing:
      icon: mdi:play
    scene.movie_stopped:
      icon: mdi:stop
    device_tracker.Imprimante:
      icon: mdi:printer
    device_tracker.dellxps:
      icon: mdi:laptop
    device_tracker.milight:
      icon: mdi:wifi
    device_tracker.wifi:
      icon: mdi:access-point
    device_tracker.soksabai_wifi:
      icon: mdi:laptop
    device_tracker.nut1:
      icon: mdi:face
    device_tracker.nut2:
      icon: mdi:face

# Track the sun
sun:

recorder:
  purge_days: 14

logbook:
  exclude:
    domains:
      - sun
      - cover
      - switch

# Enables support for tracking state changes over time.
history:
# View all events in a logbook
#logbook:

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

config:

# Expose home-assistant metadata over bonjour
zeroconf:

media_player:
  platform: kodi
  host: 192.168.0.13
  port: 8080
  name: KoKodi

# Prediction of weather
sensor:
  - platform: yr
  - platform: speedtest
    minute: 5
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
  - platform: sonarr
    api_key: a08c1dbcc5254544affd9d23669bab72
    host: familleseux.net
    port: 443
    ssl: true
    urlbase: /sonarr
    days: 6
    monitored_conditions:
      - upcoming
      - wanted


device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    home_interval: 10
    interval_seconds: 120
    track_new_devices: yes
# - platform: bluetooth_le_tracker


zone:
  name: Criteo # Work
  longitude: 2.331610
  latitude: 48.878887
  icon: "mdi:desktop-tower"

zwave:
  usb_path: /dev/zwave1 #using udev rule to have stable name
  # TODO make this path more robust
  config_path: /usr/lib/python3.6/site-packages/libopenzwave-0.3.2-py3.6-linux-armv7l.egg/config
  polling_interval: 60000
  autoheal: False # is done at midnight
  device_config_domain:
    light:
      polling_intensity: 1
  #  customize:
  #    sensor.greenwave_powernode_6_port_energy_10:
  #      polling_intensity: 1

light:
  platform: limitlessled
  bridges:
    - host: 192.168.0.110
      version: 4
      port: 8899
      groups:
        - number: 1
          type: rgbw
          name: Table à manger
        - number: 2
          type: rgbw
          name: Salon

switch:
  - platform: command_line
    switches:
      capodimonte_led:
        command_on: sudo systemctl start raspberry_led
        command_off: sudo systemctl stop raspberry_led
        command_state: systemctl is-active raspberry_led > /dev/null 2>&1
      nzbget_pause:
        command_on: "curl -XPOST capodimonte/nzbget/jsonrpc -d '{\"method\": \"pausepost\"}' && curl -XPOST capodimonte/nzbget/jsonrpc -d '{\"method\": \"pausedownload\"}'"
        command_off: "curl -XPOST capodimonte/nzbget/jsonrpc -d '{\"method\": \"scheduleresume\", \"params\": [1]}'"
        command_state: "curl -s capodimonte/nzbget/jsonrpc -d '{\"method\": \"status\"}' |grep -q 'Paused\" : true'"

cover:
  - platform: command_line
    covers:
      volets_salon:
        command_open: curl -s http://192.168.0.20/up
        command_close: curl -s http://192.168.0.20/down
        command_stop: curl -s http://192.168.0.20/down # can't do better for now
        command_state: curl -s http://192.168.0.20/status

input_boolean:
  light_control_by_kokodi:
    name: Kokodi controle lumière du salon
    initial: on
    icon: mdi:toggle-switch

shell_command:
  classical_music_on_kodi: /var/lib/hass/play_random_classical_music_kodi.sh
  radio_swiss_classic: /var/lib/hass/play_radio_swiss_classic.sh

script:
  radio_swiss_classic:
    alias: Launch Swiss Classic Music
    sequence:
      - alias: start
        service: shell_command.radio_swiss_classic
  restart_ha:
    alias: Restart HA
    sequence:
      - alias: Restart HA
        service: homeassistant.restart
  heal_zwave:
    alias: Heal ZWave network
    sequence:
      - alias: heal
        service: zwave.heal_network
      - alias: soft_reset
        service: zwave.soft_reset

  shower_on:
    alias: Shower On
    sequence:
      - alias: music
        service: shell_command.classical_music_on_kodi
      - alias: wait for a few seconds
        delay:
          seconds: 5
      - alias: light on
        service: light.turn_on
        data:
          entity_id: group.sdb_parents
          brightness: 20
      - alias: wait for a few seconds
        delay:
          seconds: 5
      - alias: light on
        service: light.turn_on
        data:
          entity_id: group.sdb_parents
          brightness: 40

  bedtime:
    alias: Fin de soirée
    sequence:
      - alias: Switch to white
        service: light.turn_on
        data:
          entity_id: group.salon
          transition: 1
          brightness: 10
          color_name: white
      - alias: Switch on light
        service: light.turn_on
        data:
          entity_id: light.salon
          transition: 10
          brightness: 215
          color_name: white
      - alias: wait 10 seconds for pipeline
        delay:
          seconds: 10
      - alias: wait until we go to bed
        delay:
          seconds: 60
      - alias: Slowly dim light off
        service: light.turn_off
        data:
          entity_id: light.salon
          transition: 60
  # this script must be killed before being launched
  bathroom_light_countdown:
    alias: Countdown until bathroom shutdown
    sequence:
      - alias: Wait countdown
        delay:
          seconds: 60
      - alias: Slowly dim light off
        service: light.turn_off
        data:
          entity_id: group.sdb_parents
          transition: 60

  diving_submarine:
    alias: Sous Marin
    sequence:
      - alias: Move lights to red
        service: light.turn_on
        data:
          entity_id: group.salon
          transition: 5
          brightness: 60
          color_name: red
      - alias: Move roller shutter down
        service: covers.close_cover
        data:
          entity_id: covers.volets_salon



# Grouped states should share the same type of states (ON/OFF or HOME/NOT_HOME)
group: !include groups.yaml

scene:
  - name: Reset to white
    entities:
      light.table_a_manger:
        state: on
        transition: 5
        brightness: 75
        color_name: white
      light.salon:
        state: on
        transition: 5
        brightness: 75
        color_name: white
  - name: Movie Playing
    entities:
      light.table_a_manger:
        state: on
        transition: 5
        brightness: 75
        color_name: blue
      light.salon:
        state: off
        transition: 5
      script.bedtime:
        state: off
      switch.nzbget_pause:
        state: on
  - name: Movie Paused
    entities:
      light.table_a_manger:
        state: on
        transition: 5
        brightness: 75
        color_name: white
      light.salon:
        state: on
        transition: 5
        brightness: 75
        color_name: white
      script.bedtime:
        state: off
  - name: Movie Stopped
    entities:
      script.bedtime:
        state: on
      switch.nzbget_pause:
        state: off
  - name: Shower on
    entities:
      script.shower_on:
        state: on
  - name: LateMorning
    entities:
      covers.volets_salon:
        state: open

automation:
  - alias: Enable light control by kokodi in the evening
    trigger:
      platform: time
      seconds: 0
      minutes: 0
      hours: 18
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.light_control_by_kokodi
  - alias: Disable light control by kokodi in the evening
    trigger:
      platform: time
      seconds: 0
      minutes: 0
      hours: 1
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.light_control_by_kokodi


  - alias: Activate movie playing scene
    trigger:
      platform: state
      entity_id: media_player.kokodi
      to: playing
    condition:
      - condition: state
        entity_id: input_boolean.light_control_by_kokodi
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.movie_playing
  - alias: Activate movie paused scene
    trigger:
      platform: state
      entity_id: media_player.kokodi
      from: playing
      to: paused
    condition:
      - condition: state
        entity_id: input_boolean.light_control_by_kokodi
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.movie_paused
  - alias: Activate movie stopped scene
    trigger:
      platform: state
      entity_id: media_player.kokodi
      to: idle
    condition:
      - condition: state
        entity_id: input_boolean.light_control_by_kokodi
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.movie_stopped


  - alias: Trigger capodimonte led on sun rise/set events
    trigger:
      platform: sun
      event: sunset
    action:
      service_template: >-
        switch.turn_{% if trigger.event == "sunrise" %}on{% else %}off{% endif %}
      entity_id: switch.capodimonte_led

  - alias: Automatic switch off in parents bathroom
    trigger:
      platform: state
      entity_id: group.sdb_parents
      from: 'off'
      to: 'on'
    action:
      - service: script.turn_off
        entity_id: script.bathroom_light_countdown
        #- service: script.turn_on
        #entity_id: script.bathroom_light_countdown

  - alias: WakeUp routine
    trigger:
      platform: time
      after: '07:00:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: home
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      service: light.turn_on
      entity_id: group.sdb_parents
      data:
        brightness: 20
  - alias: Switch off bathroom time in the morning
    trigger:
      platform: time
      after: '07:25:00'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: home
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      service: light.turn_off
      entity_id: group.sdb_parents

  - alias: Turn on music when dash button is pressed (day)
    trigger:
      platform: event
      event_type: device_lease_44:65:d:b:aa:e6 # amazon dash "simple human"
    condition:
      - condition: time
        after: '07:00:00' # avoid night errors
        before: '19:30:00'
      - condition: state
        entity_id: media_player.kokodi
        state: idle
    action:
      service: shell_command.radio_swiss_classic

  - alias: Play/Pause kodi when dash button pressed (evening)
    trigger:
      platform: event
      event_type: device_lease_44:65:d:b:aa:e6 # amazon dash "simple human"
    condition:
      - condition: time
        after: '19:30:00'
        before: '00:00:00'
    action:
      service: media_player.media_play_pause
      entity_id: media_player.kokodi

logger:
  logs:
    homeassistant.components.device_tracker: debug
