from canto.extra import *

#add("http://www.roc14.org/component/ninjarsssyndicator/?feed_id=2", tags = ["Alice Millat"])
add("http://about-gnulinux.info/dotclear/index.php?feed/atom", tags=["A propos de GNU/Linux"])
add("http://abstrusegoose.com/feed", tags=["Abstruse Goose"])
add("http://alan.petitepomme.net/cwn/cwn.rss", tags=["Caml Weekly News"])
add("http://alaska-kamtchatka.blogspot.com/feeds/posts/default?alt=rss", tags=["Alaska Ataca a Kamtchatka"])
add("http://algorythmes.blogspot.com/feeds/posts/default?alt=rss", tags=["AlgoRythmes"])
add("http://blog.admin-linux.org/category/logiciels-libres/feed", tags=["L'admin sous Linux - Blog Libre » Logiciels Libres"])
add("http://blog.admin-linux.org/feed", tags=["L'admin sous GNU / Linux - Blog Libre"])
add("http://blog.andrew.net.au/index.rss", tags=["Diary of a geek"])
add("http://blog.chromium.org/feeds/posts/default?alt=rss", tags=["Chromium Blog"])
add("http://blog.crimenumerique.fr/feed/", tags=["Criminalités numériques"])
add("http://blog.lefigaro.fr/flux.php?blog=17", tags=["Le joueur se lève"])
add("http://blog.lefigaro.fr/flux.php?blog=19", tags=["Etreintes digitales"])
add("http://blog.lefigaro.fr/flux.php?blog=32", tags=["Droit des technologies avancées"])
add("http://blog.nicolargo.com/feed", tags=["Le blog de NicoLargo"])
add("http://blog.opensyd.fr/feed/", tags=["openSYD"])
add("http://blog.theclimber.be/?feed/category/Alpinisme-et-escalade/atom", tags=["theClimber.be - Alpinisme et Escalade"])
add("http://blog.theclimber.be/?feed/category/Informatique/atom", tags=["theClimber.be - Informatique"])
add("http://blogs.valvesoftware.com/feed/?cat=7", tags=["Valve Linux team blog"])
add("http://blog.xkcd.com/feed/", tags=["xkcd"])
add("http://blogues.ebsi.umontreal.ca/jms/index.php/feed/rss2", tags=["Bloc-notes de Jean-Michel Salaün"])
add("http://caml.inria.fr/news.fr.rss", tags=["Le Langage Caml"])
add("http://carlchenet.wordpress.com/category/debian-fr/feed/", tags=["Le blog de Carl Chenet » debian-fr"])
add("http://cherryonthe.popnews.com/feed/", tags=["Cherry on the..."])
add("http://chromeos-france.fr/category/chrome-os/feed/", tags=["Chrome OS France » Chrome OS"])
add("http://codeascraft.etsy.com/feed/", tags=["Code as Craft"])
add("http://codingly.com/feed/", tags=["Codingly"])
add("http://doneed.net/b/feed/", tags=["AddiKT1ve | doneed.net"])
add("http://dutherenverseauborddelatable.wordpress.com/feed/", tags=["Il y a du thé renversé au bord de la table"])
add("http://eigenclass.org/R2/feeds/rss2/", tags=["eigenclass"])
add("http://engineering.foursquare.com/feed/", tags=["Foursquare Engineering Blog"])
add("http://experiencelinuxienne.blogspot.com/feeds/posts/default?alt=rss", tags=["Linux et Compagnie"])
add("http://feedproxy.google.com/2803", tags=["2803, le blog web 2.0, Internet et technologies"])
add("http://feeds.delicious.com/v2/rss/palpitt?count=15", tags=["Delicious/palpitt"])
add("http://feeds.feedburner.com/FredericDeVillamilcom", tags=["Le Rayon UX : Le Rayon UX | La radiographie du Web en temps presque réel"])
add("http://feeds.feedburner.com/GoogleOperatingSystem", tags=["Google Operating System"])
add("http://feeds.feedburner.com/HighScalability", tags=["High Scalability"])
add("http://feeds.feedburner.com/OxydeDeChromeOs", tags=["Oxyde de Chrome OS"])
add("http://feeds.feedburner.com/ThisIsWhyImBroke", tags=["ThisIsWhyImBroke.com"])
add("http://feeds.feedburner.com/bleebot", tags=["TechTrends"])
add("http://feeds.feedburner.com/bouletcorp", tags=["bouletcorp - le blog"])
add("http://feeds.feedburner.com/codinghorror/", tags=["Coding Horror"])
add("http://feeds.feedburner.com/debuggable", tags=["Debuggable.com - Blog"])
add("http://feeds.feedburner.com/gtutor", tags=["Google Tutor"])
add("http://feeds.feedburner.com/labandepasdessinee", tags=["La Bande Pas Dessinée"])
add("http://feeds.feedburner.com/littlebigdetails", tags=["Little Big Details"])
add("http://feeds.feedburner.com/mongotips", tags=["MongoTips by John Nunemaker"])
add("http://feeds.feedburner.com/nosql", tags=["myNoSQL"])
add("http://feeds.feedburner.com/siat-mongodb", tags=["Snail in a Turtleneck » MongoDB"])
add("http://feeds.feedburner.com/xg_blognotes", tags=["XG_BlogNotes"])
add("http://feeds.labnol.org/labnol", tags=["Digital Inspiration"])
add("http://feeds.wordaligned.org/wordaligned", tags=["Word Aligned"])
add("http://francoisgeff.com/feed/", tags=["François Geff"])
add("http://frandigou.blogspot.com/feeds/posts/default?alt=rss", tags=["Geff"])
add("http://frederic.bezies.free.fr/blog/?feed=rss2", tags=["Le Weblog de Frederic Bezies"])
add("http://gege2061.homecomputing.fr/feed/", tags=["Gege2061's blog"])
add("http://gmailblog.blogspot.com/feeds/posts/default?alt=rss", tags=["Gmail Blog"])
add("http://google-opensource.blogspot.com/feeds/posts/default?alt=rss", tags=["Google Open Source Blog"])
add("http://googledocs.blogspot.com/feeds/posts/default?alt=rss", tags=["Docs Blog"])
add("http://images.math.cnrs.fr/spip.php?page=backend", tags=["Images des mathématiques"])
add("http://imil.net/wp/feed/", tags=["Emile \"iMil\" Heitor 's home"])
add("http://internetactu.blog.lemonde.fr/feed/", tags=["InternetActu"])
add("http://interstices.info/feed/Rss2.jsp?id=c_13634", tags=["Interstices RSS"])
add("http://julien.danjou.info/blog/index.xml", tags=["jd:/dev/blog"])
add("http://kindlewallpapers.tumblr.com/rss", tags=["Kindle Wallpapers"])
add("http://libre-ouvert.toile-libre.org/feed.php?rss", tags=["Libre et ouvert"])
add("http://linux-attitude.fr/feed", tags=["Linux Attitude"])
add("http://linux-attitude.fr/feed/atom", tags=["Linux Attitude"])
add("http://linux.leunen.com/?feed=rss2&cat=15", tags=["Autour de Linux » python"])
add("http://linux.leunen.com/?feed=rss2&cat=5", tags=["Autour de Linux » Ubuntu"])
add("http://linuxfr.org/backend/journaux/rss20.rss", tags=["DLFP - Journaux"])
add("http://linuxfr.org/backend/news/rss20.rss", tags=["DLFP - Dépêches"])
add("http://linuxfr.org/journaux.atom", tags=["LinuxFr.org : les journaux"])
add("http://linuxfr.org/news.atom", tags=["LinuxFr.org : les dépêches"])
add("http://linuxmanua.blogspot.com/feeds/posts/default", tags=["Linux Manua"])
add("http://marie-issy-munich.blogspot.com/feeds/posts/default?alt=rss", tags=["Marie Issy-Munich"])
add("http://martin.ankerl.com/category/coding/feed/", tags=["Martin Ankerl » coding"])
add("http://martin.ankerl.com/category/programming/feed/", tags=["Martin Ankerl » programming"])
add("http://mauvaisgout.net/feed", tags=["mauvaisgout.net"])
add("http://medspx.homelinux.org/blog/index.rss20", tags=["Where is it ?"])
add("http://michel-eudes.net/blog/rss.php", tags=["Conseils et trucs de figaro"])
add("http://montmartre-altitude.blogspot.com/feeds/posts/default?alt=rss", tags=["Montmartre altitude"])
add("http://mrpouit.free.fr/?feed=rss2", tags=["blogibus memera?"])
add("http://nicolas.kruchten.com/content/feed/", tags=["nicolas.kruchten.com"])
add("http://notch.tumblr.com/rss", tags=["The Word of Notch"])
add("http://nuts-and-bolts-of-cakephp.com/feed/", tags=["nuts and bolts of cakephp"])
add("http://ocaml.janestreet.com/?q=rss.xml", tags=["ocaml.janestreet.com - Comments"])
add("http://owni.fr/categorie/une/feed/", tags=["OWNI"])
add("http://passeurdesciences.blog.lemonde.fr/feed/", tags=["Passeur de sciences"])
add("http://philippe.scoffoni.net/feed/", tags=["Philippe Scoffoni"])
add("http://planet-fr.debian.net/rss20.xml", tags=["Planet Debian-FR"])
add("http://planet.archlinux.org/atom.xml", tags=["Planet Arch Linux"])
add("http://planet.auto-hebergement.fr/feed.php?type=rss", tags=["Planet auto-hébergement"])
add("http://playtime.blog.lemonde.fr/feed/", tags=["Playtime"])
add("http://rats-bleus.blogspot.com/feeds/posts/default?alt=rss", tags=["Les rats bleus"])
add("http://reyt.net/feed/", tags=["Jean-Nicolas Reyt"])
add("http://rss.futura-sciences.com/fs/dossiers", tags=["Les derniers dossiers de Futura-Sciences"])
add("http://rss.wikio.fr/search/Dominique+Seux.rss", tags=["Wikio - Dominique Seux"])
add("http://sebsauvage.net/rhaa/rss_fulltext.php", tags=["sebsauvage.net"])
add("http://securiteoff.blogspot.com/feeds/posts/default?alt=rss", tags=["Le poil à gratter des antivirus et des logiciels de sécurité"])
add("http://spikedmath.com/atom.xml", tags=["Spiked Math"])
add("http://stevehanov.ca/blog/?atom", tags=["Steve Hanov's Programming Blog"])
add("http://syndication.thedailywtf.com/TheDailyWtf", tags=["The Daily WTF"])
add("http://t37.net/", tags=["Ergonomie web, Ruby on Rails et Architecture de l'information :"])
add("http://tanguy.ortolo.eu/blog/feed/atom", tags=["Tanguy Ortolo"])
add("http://tech.just-imho.net/atom.xml", tags=["just-imho: tech"])
add("http://techblog.appnexus.com/feed/", tags=["AppNexus Tech Blog"])
add("http://techblog.netflix.com/feeds/posts/default?alt=rss", tags=["The Netflix Tech Blog"])
add("http://theclimber.fritalk.com/feed/atom", tags=["theClimber"])
add("http://timbroder.com/feed", tags=["timbroder.com"])
add("http://tuxicoman.jesuislibre.net/feed", tags=["Tuxicoman"])
add("http://ubunteros.tuxfamily.org/spip.php?page=backend", tags=["Linux On The Root !"])
add("http://univers-libre.net/index.php/feed/", tags=["Univers Libre"])
add("http://vidberg.blog.lemonde.fr/feed/", tags=["L'actu en patates"])
add("http://www.42experiment.org/feed/", tags=["The .42 Experiment"])
add("http://www.actumaths.com/actumaths.xml", tags=["Actumaths"])
add("http://www.antoinebenkemoun.fr/feed/", tags=["Antoine Benkemoun"])
add("http://www.archlinux.org/feeds/news/", tags=["Arch Linux: Recent news updates"])
add("http://www.arkandis.com/feed/", tags=["Arkandis"])
add("http://www.bomahy.nl/hylke/blog/feed/", tags=["Design Monkey"])
add("http://www.christian-faure.net/feed/", tags=["Christian Fauré"])
add("http://www.clapico.com/feed/", tags=["Clapico's Blog"])
add("http://www.croc-informatique.fr/feed/", tags=["Croc-Informatique.fr"])
add("http://www.csquad.org/feed/", tags=["Christophe Nowicki"])
add("http://www.cyrille-borne.com/index.php?feed/atom", tags=["Le blog de Cyrille BORNE"])
add("http://www.diaryofaninja.com/rss/main", tags=["Diary of a Ninja"])
add("http://www.direnepasdire.org/?format=feed&type=rss", tags=["Académie française - Dire, ne pas dire - Dire, ne pas dire"])
add("http://www.formation-cakephp.com/feed", tags=["Formation CakePHP"])
add("http://www.framablog.org/index.php/feed/atom", tags=["Framablog"])
add("http://www.geeek.org/feed/atom", tags=["Blog de Geeek, le blog geek ..."])
add("http://www.generation-libre.com/feed/", tags=["Generation Libre"])
add("http://www.generation-linux.fr/index.php?feed/rss2", tags=["Génération Linux"])
add("http://www.goopilation.com/feed", tags=["Goopilation"])
add("http://www.jesuislibre.org/backend_xml.php3", tags=["Je Suis Libre"])
add("http://www.labo-microsoft.com/tips/rss/", tags=["Les Tips du Laboratoire Microsoft"])
add("http://www.larsen-b.com/feed", tags=["Jkx@home"])
add("http://www.laviemoderne.net/clapotis/feed/rss.html", tags=["Clapotis - La vie moderne"])
add("http://www.laviemoderne.net/lames-de-fond/feed/rss.html", tags=["Lames de fond - La vie moderne"])
add("http://www.linux-mag.com/feed/", tags=["Linux Magazine"])
add("http://www.mangetamain.fr/feed", tags=["MANGE TA MAIN!"])
add("http://www.math-linux.com/spip.php?page=backend&id_rubrique=17", tags=["math-linux.com"])
add("http://www.math-linux.com/spip.php?page=backend&id_rubrique=19", tags=["math-linux.com"])
add("http://www.mybusinesseducation.fr/taxonomy/term/44/0/feed", tags=["My Business Education - seth godin"])
add("http://www.oezratty.net/wordpress/feed/", tags=["Opinions Libres"])
add("http://www.planet-libre.org/feed.php?type=rss", tags=["Planet Libre"])
add("http://www.prospective-numerique.gouv.fr/rss.xml", tags=["Flux RSS des actualités du SEPDEN"])
add("http://www.rabbitmq.com/blog/feed/", tags=["RabbitMQ"])
add("http://www.reddit.com/r/archlinux/.rss", tags=["Arch Linux - Keeping it Simple"])
add("http://www.reddit.com/r/mongodb/.rss", tags=["MongoDB"])
add("http://www.regardscitoyens.org/feed/", tags=["Regards Citoyens"])
add("http://www.road2mayotte.org/blog/?feed=rss2", tags=["Road2Mayotte"])
add("http://www.rockstarprogrammer.org/rss/full/", tags=["RockStarProgrammer - Full Posts"])
add("http://www.royans.net/arch/feed/", tags=["Scalable web architectures"])
add("http://www.rue89.com/category/typepublication/pause-cafe/feed", tags=["Pause café"])
add("http://www.sanctuaire.fr.eu.org/rss.php", tags=["Sanctuaire numérique"])
add("http://www.simple-it.fr/blog/index.php?feed/atom", tags=["Simple IT : le blog"])
add("http://www.smbc-comics.com/rss.php", tags=["Saturday Morning Breakfast Cereal (updated daily)"])
add("http://www.sparkleshare.org/news.xml", tags=["SparkleShare News"])
add("http://www.synergeek.fr/feed/", tags=["Sur le fil technologique"])
add("http://www.thedoghousediaries.com/?feed=rss2", tags=["www.thedoghousediaries.com/?feed=rss2"])
add("http://www.think-underground.com/feed/atom", tags=["Bienvenue sur Think-Underground.com"])
add("http://www.unpeud.info/component/content/frontpage/frontpage?format=feed&type=rss", tags=["Mathématiques - Informatique"])
add("http://www.webmonkey.com/feed/", tags=["Webmonkey"])
add("http://www.zorgloob.com/feed/", tags=["Zorgloob"])
add("http://xaviergorce.com/?feed=rss2", tags=["Xavier Gorce"])
add("http://xhtml.net/rss.php", tags=["XHTML.net"])
add("http://xkcd.com/rss.xml", tags=["xkcd.com"])
add("http://yeknan.free.fr/dc2/index.php?feed/category/Ubuntu/atom", tags=["yeKblog - Ubuntu"])
add("http://zythom.blogspot.com/feeds/posts/default", tags=["Zythom - Blog d'un informaticien expert judiciaire"])
add("https://mozillalabs.com/feed/", tags=["Mozilla Labs"])



link_handler("chromium \"%u\"")
image_handler("feh \"%u\"")

#unread stories
colors[1] = ("yellow", "default")
#read stories
colors[2] = ("blue", "default")
#image links color
colors[6] = ("magenta", "default")



#display also the author of stories
r = get_default_renderer()
add_info(r,"Author")


keys['/'] = search_filter
keys['y'] = yank


default_tag_sorts([by_unread])
filters=[show_unread, None]


#cursor behavior :
cursor_type = "edge"
cursor_scroll = "scroll"
cusrsor_edge = 10
