#!/usr/bin/bash

# I've fully removed this part. It used to call "ip link" to detect vpn presence which is very slow when iwd is starting
# moreover the code was never adapted to latest vpn setup so it was effectively useless

sleep 30
exit 0
